application:
  cors:
    allowed-origins:
      - https://whatwhere-admin.codo.ee/
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: '*'
    allow-credentials: false
    max-age: 1800

firebase:
  config:
