logging:
  level:
    ee.spacexy.whatwhere.service: DEBUG
    org.springframework.security: TRACE

logger:
  appender: DEVELOPMENT

datasource:
  url: "jdbc:postgresql://localhost:5432/whatwhere"
  username: whatwhere
  password: whatwhere

liquibase:
  url: "jdbc:postgresql://localhost:5432/whatwhere"
  username: whatwhere
  password: whatwhere

application:
  cors:
    allowed-origins:
      - https://whatwhere-admin.codo.ee/
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: '*'
    allow-credentials: false
    max-age: 1800


